DROP TABLE IF EXISTS compilation_events;
DROP TABLE IF EXISTS participation_requests;
DROP TABLE IF EXISTS compilations;
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS locations;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    email VARCHAR(254) NOT NULL UNIQUE CHECK(LENGTH(email) >= 6),
    name VARCHAR(250) NOT NULL CHECK(LENGTH(name) >= 2)
    );

CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    latitude FLOAT NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude FLOAT NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    radius FLOAT DEFAULT 0 CHECK (radius >= 0),
    type VARCHAR(40) NOT NULL,
    CONSTRAINT chk_type CHECK (type IN ('CONFERENCE_HALL',
                                        'OPEN_AIR',
                                        'COWORKING',
                                        'STADIUM',
                                        'THEATER',
                                        'RESTAURANT',
                                        'OTHER'))
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    description VARCHAR(7000) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    paid BOOLEAN DEFAULT false,
    participant_limit INT DEFAULT 0,
    request_moderation BOOLEAN DEFAULT FALSE,
    location_id BIGINT NOT NULL REFERENCES locations ,
    state VARCHAR(20) DEFAULT 'PENDING',
    published_on TIMESTAMP,
    created_on TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    category_id BIGINT REFERENCES categories,
    user_id BIGINT REFERENCES users ON DELETE CASCADE,
    confirmed_requests INTEGER,
    CONSTRAINT chk_status CHECK (state IN ('PENDING', 'REJECTED', 'PUBLISHED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS compilations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL UNIQUE CHECK (length(title) >= 1),
    pinned BOOLEAN DEFAULT FALSE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS compilation_events(
    compilation_id BIGINT NOT NULL REFERENCES compilations(id) ON DELETE CASCADE,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    PRIMARY KEY (compilation_id, event_id)
    );

CREATE TABLE IF NOT EXISTS participation_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP,
    event_id BIGINT NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) DEFAULT 'PENDING',
    CONSTRAINT chk_request_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'CANCELED')),
    CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
    );