drop table if exists endpoint_hit;

CREATE table IF NOT EXISTS endpoint_hit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    app VARCHAR(255) NOT NULL,
    uri VARCHAR(255) NOT NULL,
    user_ip VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL
    );